#!/bin/bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install git
git clone https://github.com/ZeroStride/bugoutbag.git $HOME/bugoutbag

# Add bugoutbag to .bash_profile
grep -q "bugoutbag" $HOME/.bash_profile || echo $'\n[[ -s "$HOME/bugoutbag/.bash_profile" ]] && source "$HOME/bugoutbag/.bash_profile" # Load the bugoutbag' >> $HOME/.bash_profile

# Fake passports
brew cask install sublime-text
brew cask install 1password

# Mustaches
curl -sSL https://get.rvm.io | bash -s stable --ruby

# Drobo
brew tap homebrew/cask-drivers
brew cask install drobo-dashboard

# Android dev
brew cask install homebrew/cask-versions/java8
brew cask install android-sdk
brew cask install android-studio
brew install getsentry/tools/sentry-cli

# iOS dev
brew install clang-format

# Docker and CircleCI
brew cask install docker
brew install --ignore-dependencies circleci

# Alfred
brew cask install alfred
open /Applications/Alfred\ 3.app

# Comms
brew cask install slack
brew cask install discord

# uBlock Origin
open "https://safari-extensions.apple.com/details/?id=com.el1t.uBlock-3NU33NW2M3"
