#!/bin/bash
post_install=""

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install git
git config --global user.name "Pat Wilson"
git config --global user.email "zerostride@gmail.com"

git clone https://github.com/ZeroStride/bugoutbag.git $HOME/bugoutbag

# Add bugoutbag to .bash_profile
grep -q "bugoutbag" $HOME/.bash_profile || echo $'\n[[ -s "$HOME/bugoutbag/.bash_profile" ]] && source "$HOME/bugoutbag/.bash_profile" # Load the bugoutbag' | cat - $HOME/.bash_profile > temp && mv temp $HOME/.bash_profile

# Fake passports
brew cask install sublime-text
brew cask install 1password

# Mustaches
curl -sSL https://get.rvm.io | bash -s stable --ruby

# Drobo
brew tap homebrew/cask-drivers
brew cask install drobo-dashboard

# Android dev
brew cask install homebrew/cask-versions/java8
brew cask install android-sdk
brew cask install android-studio
brew install getsentry/tools/sentry-cli

# iOS dev
brew install clang-format
brew install usbmuxd --HEAD
brew install --HEAD libimobiledevice
brew install --HEAD ideviceinstaller
# sudo chmod -R 777 /var/db/lockdown
post_install="${post_install}For libimobiledevice:\nsudo chmod -R 777 /var/db/lockdown\n\n"

# Other Dev
brew install astyle

# Docs
pip3 install sphinx
pip3 install sphinx-autobuild
pip3 install sphinx_rtd_theme

# Ruby 2.2.2 shennanagins
brew install libiconv
brew link libiconv

# MySQL for Teak dev
brew install mysql@5.7
brew services start mysql@5.7

# Postgres
brew install postgresql

# Completely removing mysql:
# https://coderwall.com/p/os6woq/uninstall-all-those-broken-versions-of-mysql-and-re-install-it-with-brew-on-mac-mavericks

# Docker and CircleCI
brew cask install docker
brew install --ignore-dependencies circleci

# Alfred
brew cask install alfred
open /Applications/Alfred\ 3.app

# Comms
brew cask install slack
brew cask install discord

# uBlock Origin
open "https://safari-extensions.apple.com/details/?id=com.el1t.uBlock-3NU33NW2M3"

# Post-install notes
printf "$post_install" | subl
